// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unludpreairsjszzkwbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubHVkcHJlYWlyc2pzenprd2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODE0MDAsImV4cCI6MjA2MzI1NzQwMH0.qZ1_BO7GxRBs3Aosb47qHb2nU2U3O4keFJAMZPDIOzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);